# access the hexo editor directly
local: false

# the username to login hexo editor
username: joseph

# the password for logining hexo editor
password: 111111

# the blog directory
base_dir: ./docs

# port
port: 2048
